### ISSUE TITLE
How do I get  access to individual camera frames?

### ISSUE THREAD

**Issue by walchko** [maartenbreddels/ipywebrtc#4]
I want to use this to do work with OpenCV programming in python. How do I get access to the frames coming in from my camera?

**Comment by martinRenou** [comment]
With the new release you can use ImageRecorder :) and you'll get access to the frames using `ImageRecorder.image.value`

**Comment by jiapei100** [comment]
> With the new release you can use ImageRecorder :) and you'll get access to the frames using `ImageRecorder.image.value`

Well, it looks I've got to save an image before accessing the frames?
If I don't click on the **snapshot** button, it looks `ImageRecorder.image.value=b''` which is actually **empty**.
What's more, is there a way directly from **io.BytesIO()** to **numpy ndarray** (say, **OpenCV**), rather than using **PIL** **Image**?
